apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  secretStoreRef:
    name: gcp-secretstore
    kind: ClusterSecretStore
  target:
    name: grafana-admin-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: grafana-admin-secret