apiVersion: v1
kind: ConfigMap
metadata:
  name: guild-configmap
  labels:
    app: guild
data:
  NODE_ENV: "development"
  APP_PORT: "3000"
  GRPC_PORT: "5000"
  DB_HOST: "pgbouncer-config"
  DB_PORT: "5432"
  DB_NAME: "viscord_guild"
  USER_SERVICE_HOST: "user-service"
  USER_SERVICE_PORT: "3000"
  USER_SERVICE_GRPC_PORT: "5000"
  MESSAGE_SERVICE_HOST: "message-service"
  MESSAGE_SERVICE_PORT: "8080"
  MESSAGE_SERVICE_GRPC_PORT: "9090"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://opentelemetry-collector.monitoring:4318"
  RMQ_HOST: "message-broker-service"
  RMQ_PORT: "5672"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  CDN_ENDPOINT: "https://cdn.dev.viscord.app"
  BUCKET_NAME: "viscord-dev-409684965426-ap-southeast-3-an"
  S3_REGION: "ap-southeast-3"