apiVersion: v1
kind: Service
metadata:
  name: message-broker
  labels:
    app: message-broker
spec:
  selector:
    app: message-broker
  ports:
    - name: rmq-dashboard
      protocol: TCP
      port: 15672
      targetPort: rmq-dashboard
    - name: rmq-api
      protocol: TCP
      port: 5672
      targetPort: rmq-api