loki:
  commonConfig:
    replication_factor: 1
  schemaConfig:
    configs:
      - from: "2020-01-01"
        store: tsdb
        object_store: gcs
        schema: v13
        index:
          prefix: index_
          period: 24h
  limits_config:
    volume_enabled: true
    retention_period: 720h
  compactor:
    retention_enabled: true
    delete_request_store: gcs
  ruler:
    enable_api: true
      # alertmanager_url: http://prom:9093 # The URL of the Alertmanager to send alerts (Prometheus, Mimir, etc.)
  storage:
    type: gcs
    bucketNames:
      chunks: viscord-loki-chunks-dev
      ruler: viscord-loki-ruler-dev
  auth_enabled: false

backend:
  replicas: 1
  
write:
  replicas: 1

read:
  replicas: 1

chunksCache:
  allocatedMemory: 1024
  allocatedCPU: 250m
  
serviceAccount:
    create: false
    name: loki-ksa

