apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
configMapGenerator:
- envs:
  - config.env
  name: auth-config
secretGenerator:
- envs:
  - secret.env
  name: auth-secret
patches:
- target:
    kind: Deployment
    name: auth-deployment
  path: replicas.yaml
images:
- name: vincentramaputra/viscord-auth-service
  newTag: sha-8b8f623