apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: auth
          envFrom:
          - configMapRef:
              name: db-config
          - secretRef:
              name: auth-secret
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"