apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: cloud-sql-proxy
          args:
            - "-p=5432"
            - "--private-ip"
            - "project-d29ff022-8c65-49c1-9db:asia-southeast2:viscord-dev"
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "32Mi"
        - name: auth
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"