apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-secret
spec:
  secretStoreRef: 
    name: aws-secretstore
    kind: ClusterSecretStore
  target:
    name: auth-secret
    template:
      data:
        DB_USER: "{{ .username }}"
        DB_PASSWORD: "{{ .password  }}"
        JWT_SECRET: "{{ .JWT_SECRET }}"
  dataFrom:
  - extract:
      key: app-db-secret-dev
  - extract:
      key: APP_DEV