apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-secret
spec:
  secretStoreRef: 
    name: aws-secretstore
    kind: ClusterSecretStore
  target:
    name: auth-secret
  dataFrom:
  - extract:
      key: app-db-secret-dev