apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
labels:
  - includeSelectors: true
    includeTemplates: true
    pairs:
      app: auth
resources:
  - ./deployment.yaml
  - ./service.yaml
  - ./serviceaccount.yaml
