api:
  dashboard: true
  insecure: false

ingressRoute:
  dashboard:
    enabled: true
    entryPoints:
      - websecure
    matchRule: Host(`traefik.dev.viscord.app`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
    tls:
      certResolver: letsencrypt

ports:
  web:
    port: 80
    # http:
    #   redirections:
    #     entryPoint:
    #       to: websecure
    #       scheme: https
    #       permanent: true
  websecure:
    port: 443

service:
  type: LoadBalancer
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    external-dns.alpha.kubernetes.io/hostname: "dev.viscord.app,*.dev.viscord.app"
certificatesResolvers:
  letsencrypt:
    acme: 
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      email: "vincentramaputra123@gmail.com"
      storage: "/data/acme.json"
      httpChallenge:
        entryPoint: "web"

persistence:
  enabled: true
  size: 128Mi

securityContext:
  readOnlyRootFilesystem: false

podSecurityContext:
  fsGroup: null
  runAsGroup: 0
  runAsUser: 0
  runAsNonRoot: false


providers:
  kubernetesCRD:
    allowCrossNamespace: true

logs:
  general:
    level: DEBUG
  access:
    enabled: true
    fields:
      defaultMode: keep
      names:
        RequestPath: keep
        RequestMethod: keep
        DownstreamStatus: keep