api:
  dashboard: true
  insecure: false

ingressRoute:
  dashboard:
    enabled: true
    entryPoints:
      - web
      - websecure
    matchRule: Host(`traefik.viscord.test`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))

ports:
  web:
    port: 80
    # http:
    #   redirections:
    #     entryPoint:
    #       to: websecure
    #       scheme: https
    #       permanent: true
  websecure:
    port: 443

service:
  type: LoadBalancer
  spec:
    loadBalancerIP: 34.101.89.196

certificatesResolvers:
  letsencrypt:
    acme:
      email: "vincentramaputra123@gmail.com"
      storage: "/data/acme.json"
      httpChallenge:
        entryPoint: "web"

persistence:
  enabled: true
  size: 128Mi

podSecurityContext:
  fsGroup: null

securityContext:
  runAsUser: 65532
  runAsGroup: 65532

logs:
  general:
    level: DEBUG