apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - ../../base
  # - ./argocd-secret.yaml
  - ./ingressroute.yaml
  - ./git-credential-secret.yaml
patches:
  - path: ./argocd-cmd-params-cm.yaml