apiVersion: v1
kind: ConfigMap
metadata:
  name: guild
  labels:
    app: guild
data:
  APP_PORT: "3000"
  GRPC_PORT: "5000"
  DB_HOST: "guild-db"
  DB_PORT: "5432"
  DB_NAME: "viscord_guild"
  USER_SERVICE_HOST: "user"
  USER_SERVICE_PORT: "3000"
  MESSAGE_SERVICE_HOST: "message"
  MESSAGE_SERVICE_PORT: "3000"
  RMQ_HOST: "message-broker"
  RMQ_PORT: "5672"
  # AWS_REGION:
  # AWS_BUCKET:
  # IMAGE_ASSET_PATH:
  # REDIS_HOST: "redis"
  # REDIS_PORT: ""
  # SFU_SERVICE_HOST: "sfu"
  # SFU_SERVICE_PORT: "3000"


