apiVersion: v1
kind: ConfigMap
metadata:
  name: user-configmap
  labels:
    app: user
data:
  NODE_ENV: "development"
  APP_PORT: "3000"
  GRPC_PORT: "5000"
  # DB_HOST: "localhost"
  # DB_PORT: "5432"
  DB_NAME: "viscord_user"
  DB_SSL_REJECT_UNAUTHORIZED: "false"
  RMQ_HOST: "message-broker-service"
  RMQ_PORT: "5672"
  AUTH_SERVICE_HOST: "auth-service"
  AUTH_SERVICE_PORT: "3000"
  GUILDS_SERVICE_HOST: "guild-service"
  GUILDS_SERVICE_PORT: "3000"
  CDN_ENDPOINT: "https://cdn.dev.visord.app"
  BUCKET_NAME: "viscord-dev-409684965426-ap-southeast-3-an"
  S3_REGION: "ap-southeast-3"
