apiVersion: v1
kind: ConfigMap
metadata:
  name: user-configmap
  labels:
    app: user
data:
  APP_PORT: "3000"
  GRPC_PORT: "5000"
  # DB_HOST: "localhost"
  # DB_PORT: "5432"
  DB_NAME: "viscord_user"
  DB_SSL_REJECT_UNAUTHORIZED: "false"
  RMQ_HOST: "message-broker-service"
  RMQ_PORT: "5672"
  AUTH_SERVICE_HOST: "auth-service"
  AUTH_SERVICE_PORT: "3000"
  GUILDS_SERVICE_HOST: "guild-service"
  GUILDS_SERVICE_PORT: "3000"
  STORAGE_ENDPOINT: "https://storage.googleapis.com"
  CDN_ENDPOINT: "https://storage.googleapis.com"
  AWS_BUCKET: "viscord-dev"
  AWS_REGION: "us-east-1"
