apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: user
          envFrom:
          - configMapRef:
              name: user-configmap
          - secretRef:
              name: user-db-secret
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"