apiVersion: v1
kind: ConfigMap
metadata:
  name: message-configmap
  labels:
    app: message
data:
  DB_NAME: viscord_message 
  GUILD_SERVICE_GRPC_ADDR: guild-service:5000
  BUCKET_NAME: "viscord-dev-409684965426-ap-southeast-3-an"
  S3_REGION: "ap-southeast-3"