---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: message-secret
  namespace: default
spec:
  encryptedData:
    DB_PASSWORD: AgBN0ilWYXLYXsdmHtkpUG6mjke/ZMk12pN2uNcguAcs1rMmSEksu0fwqt0mwGCXFXT0KR6IPWC7WErMK0XAaZLotXZ8SJI/3Q/aI2j3t0Bezp9KkjRJQM7p6KJ043uDXiQpYocZT+TBh28oMAQKW3eYpLoMM2CNMYu85HLSnGePF+XoLx1oNYUkcWQd+xgUktVMwycKjmLCU0Zdx68tuHBayWzzSVEiq5w78MWg6qhYdRkQdv4EMFIotlOonN0L3XT35fV7FeaX4/g8Dy8ENCy21fAMiJYPMIRU224BujaU8UH4U3YnULLyuOcyADaVau8D/mkZs09WU3BK+2XE+ADt+sOobnS3BQ9iz59YVQcyvsc2Jl202jFfA/rIUnkl5QDloPGtPW4Jz0DJtLPP4BLlPheh8N0heTWjYnJT4iAiqNuLH+xrwVG7sndSE2f/ew3vN/ODKxxat1nWLa0FtdKyPFDmxRiReBPuEZn5I34eq8ZmgLiDBleTBm54rETyq+F2SJyCcPvLC4kC/e/74+Hfn3AmnSt6VhnL9RdPFI7VunFQzNS3Qux2ZnpfgExQHrzqHj7NEg+0W+YncV2KW1NEiCEcdw64BblCxqmVhPFeOEeDMtwaun0otl5fmauMwcFLIYMcvd1jEJFseH9gWPyt5YDG5I8pFXKbbasalxTohNKKONznHd9i+rhUlBSGB7nxtTwSDQ==
    DB_USERNAME: AgBctOS4ecwwq2kjOoWimzbCEPN6EDeassgU3Haf4bOnj8/GAOT7WBeHVbeokPOuD5vqHK4weMsW+B5zDA+UVYl905SSRjFc0ipxpYkfEeaMz+hmJP8gQk6xiMK5Boqs12huQSdUgZInTfOehA5dyKI1DfD2FvMFBqmAIluEbSL7lOAaO/rs8mASoNee10UvOJRiIw19M8Dtx+2f8ZbtHxBGMotlIoNT4W65xIWDuGq07ju4CWECSSv6x+kAe1GayLioSiIn8HKEjfJQPcve5rWAxD8VTKlqOBii+/CVRohOm+ZnYLGzb/Zl3R2CuBf57hW7GD+MxzimoZIZB0NmRCHZrG3GECdyqWbkB4ArbTPr7kKEZBOyrJOEKTh/w0KUsdtSvfxdld4Kmrqt5iaxTt+JkrU2VXXdV9DUs7BOOmj5N8MGJ0hIBG8RkI7/D3fFozXRHIJB47c3Xd0cU1dOax4gnG0xBsJC16unbI3kPfRjtKsYhpCe6IFHqbFb+GeDgcaMx0Ivjy15JiOp53NUzWt4H8nHdejhyr/poCWRZUBa6KOPWT75qbaPxrfBbsT3ivlXJZzwA++TZRH41BnIbMb/FuJbaY3r2RXPWrt46UsKQ7jxLDc2XHurEcgvG8qJvPfw3zykl+AiJ/4VzjjYFYXzkL/WWFWnUbLhBRgHT1OnGY2Gf8+xpPhWKcQZiIdTbAo03aIQ6NCauQ==
  template:
    metadata:
      labels:
        app: message
      name: message-secret
      namespace: default
