apiVersion: apps/v1
kind: Deployment
metadata:
  name: guild-deployment
spec:
  template:
    metadata:
    spec:
      serviceAccountName: guild-ksa
      containers:
      - name: guild
        image: vincentramaputra/viscord-guild-service
        envFrom:
        - configMapRef:
            name: guild-configmap
        - secretRef:
            name: guild-secret
        ports:
        - name: http
          containerPort: 3000
        - name: grpc
          containerPort: 5000
