apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app-dev
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/Laevateinn17/viscord-infra.git
      targetRevision: HEAD
      path: k8s/argocd/dev/infra
    - repoURL: https://github.com/Laevateinn17/viscord-infra.git
      targetRevision: HEAD
      path: k8s/argocd/dev/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: -1
      refresh: true