apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: message-broker-statefulset
spec:
  template:
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:4.0-management
          ports:
            - containerPort: 15672
              name: rmq-dashboard
            - containerPort: 5672
              name: rmq-api
