apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentbit
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources: 
    - repoURL: https://fluent.github.io/helm-charts
      chart: fluent-bit
      targetRevision: 0.57.5
      helm:
        valueFiles:
          - $values/k8s/platform/fluentbit/values/dev.yaml
    - repoURL: https://github.com/Laevateinn17/viscord-infra.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: -1
      refresh: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
      - ServerSideApply=true
