# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: loki-resources
#   namespace: argocd
# spec:
#   project: default
#   sources:
#     - repoURL: https://github.com/Laevateinn17/viscord-infra.git
#       path: k8s/platform/loki/overlays/dev
#       targetRevision: HEAD
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: loki
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     retry:
#       limit: -1
#       refresh: true
#     syncOptions:
#       - PruneLast=true
#       - CreateNamespace=true