apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-resources
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/Laevateinn17/viscord-infra.git
      path: k8s/platform/prometheus-stack/overlays/dev
      targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: -1
      refresh: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true