apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgbouncer-deployment
spec:
  template:
    spec:
      containers:
      - name: pgbouncer
        envFrom:
        - configMapRef:
            name: db-config
        - configMapRef:
            name: pgbouncer-config
        - secretRef:
            name: pgbouncer-secret
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
          limits:
            memory: 32Mi