apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  template:
    spec:
      serviceAccountName: user-ksa
      containers:
        - name: user
          image: vincentramaputra/viscord-user-service
          envFrom:
          - configMapRef:
              name: user-configmap
          - secretRef:
              name: user-secret
          ports:
          - name: http
            containerPort: 3000
          - name: grpc
            containerPort: 5000
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.0