apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-dev
  namespace: argocd
spec:
  project: default
  sources:
    - chart: traefik
      repoURL: https://traefik.github.io/charts
      targetRevision: 39.0.7
      helm:
        valueFiles: 
          - $values/k8s/infra/traefik/values/dev.yaml
    - repoURL: https://github.com/Laevateinn17/viscord-infra.git
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/Laevateinn17/viscord-infra.git
      targetRevision: HEAD
      path: k8s/infra/traefik/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: -1
      refresh: true
    syncOptions:
      - PruneLast=True
      - CreateNamespace=True