apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- ../../base
- ./ingressroute.yaml
patches:
- path: ./deployment-patch.yaml
images:
- name: vincentramaputra/viscord-web
  newTag: sha-85cee84
