config:
  outputs: |
    [OUTPUT]
        Name loki
        Match kube.*
        Host loki-gateway.loki.svc.cluster.local
        Port 80
        Labels job=fluentbit
        Auto_Kubernetes_Labels on
