grafana:
  additionalDataSources:
    - name: loki
      type: loki
      access: proxy
      url: http://loki-gateway.loki.svc.cluster.local
  admin:
    existingSecret: grafana-admin-secret
    userKey: user
    passwordKey: password
    