apiVersion: v1
kind: ConfigMap
metadata:
  name: message
  labels:
    app: message
data:
  DB_URL: "jdbc:postgresql://message-db:5432/viscord_message"
  GUILD_SERVICE_GRPC_ADDR: "guild:5000"
  # AWS_REGION:
  # S3_BUCKET_NAME: