apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
labels:
  - pairs:
      test: labelz
resources:
  - ../../base
  - ./resources.yaml
patches:
  - path: ./deployment-patch.yaml