apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
- ../../base
- ./ingressroute.yaml
- ./secret.yaml
- ./configmap.yaml
patches:
- path: ./deployment-patch.yaml
- path: ./serviceaccount-patch.yaml
images:
- name: vincentramaputra/viscord-user-service
  newTag: sha-bc9cd53
