apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: user-secret
spec:
  secretStoreRef:
    name: gcp-secretstore
    kind: ClusterSecretStore
  target:
    name: user-secret
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app: user
    dataFrom:
      - extract:
          key: user-service-dev
          