apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Laevateinn17/viscord-infra.git
    targetRevision: HEAD
    path: k8s/infra/dev/traefik/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: -1