apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  template:
    spec:
      serviceAccountName: user-ksa
      containers:
        - name: user
          image: vincentramaputra/viscord-user-service
          ports:
          - name: http
            containerPort: 3000
          - name: grpc
            containerPort: 5000