apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: message-ingressroute
  labels:
    app: message
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`viscord.local`) && PathPrefix(`/api/messages`) || PathRegexp(`^/api/channels/.+/messages`)
      services:
        - name: message-service
          port: 3000
      middlewares:
        - name: forward-auth
        - name: strip-api-prefix
