apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-dev
  namespace: argocd
spec:
  project: default
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: 39.0.7
    helm:
      valuesFile: k8s/infra/traefik/values/dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: -1
      refresh: true
    syncOptions:
      - PruneLast=True
      - CreateNamespace=True