apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ./ingressroute.yaml
  - ./configmap.yaml
  - ./secret.yaml
patches:
  - target:
      kind: Deployment
      name: guild-deployment
    path: ./deployment-patch.yaml
  - path: ./serviceaccount-patch.yaml