---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: guild-secret
  namespace: default
spec:
  encryptedData:
    DB_PASSWORD: AgBfpcD0+xv4U+olaKGY7vndEuZ5T5cjiPtsfyLoSELQrom079h8LCdTslP2dfJMdhB6wB1KuSFVKGPqmmpf3vZuXh026eYlm63DGCYeva0N8hBiCVSRNZnQIXTuIunedlEOO9t+wQRtQOosYYOJwioSDGaIRXKImc31TOZXwp85dnkYO7EE3azU4pczJ8UMTwMTrbPGyeeVNPgqjZoKG/pKGZyafDMfRHMxKiL71UGARrDcSktjGO75xj7tSoiBozpLTsCD2OsWBXu5oWcdYteLRWvee15oO3A29RVkU7TE9KJrKnrLvRm1E1vrQC3s0GT03gEXN0TPrfHSDjbh2eOyo2p5sNiIy0KzPgS8/RaxmH1eySVF1kfaG1sJ7J88AVbi8ogypigrSRLQds/rav51zj72dzbZch4lv7UxBhWKdU+qSehwQ5zwwqhDgcjFFE0TYla/cP0Ph0bF89O7J4pxtZFixsidM5oVibzYxBmL/hW3oOcsyTDJ1+jgybgoQbo+t5Vz9p/27fhTybsYJ0lGIx+GIfMik3cbbCbwtKpbipG8cTug94VQo1bdxi9UKp2i6DZww8/OGdcXAp/p9lbs0VkT4qPWLdYAbHyarbq/uDQb/osfIDdRWwDVfejUx+ajojzBJ5Y/tqqcza9xXrj/rIABLE5ZzG3r7lbd8MeV+NknvKqnw7gZ0aIDvbZBavQ4kTVyog==
    DB_USER: AgA7Xz3u7GtiXJ3pVawUviAgbeVW5wxL8DyQbPStYTEeJR54xCds4GDUg0kQVNIgIddH94KVgeNb9xsjvNUh09fckfCAejHrNvGiGmY+aa+pBm6QB+pEil/8p/fVjm8HNNSvIpC9vzweB9llWwennY3FUSWvImvPFp2WbSBOaJbX+tIGhFRt0Gn7Ugt9OByyN1TzsJfj+fFCbYlHG2AqtbPU05u1p86GPC/fTOkL0YUjOc01WAluUPje+PcfVrzTlNBZ8U05q+hZg96jX8rsCTjBsAZxV7k6dKuIiGjl5t7hD1R6ayLbcu1BXBXIq3zB9osJOwfG9k78TnE7QxcW0OQf/hqj9DyNveezJBEbLxuaKdANrQiM6RauxiUXbCga4ovJv3Tkn2vOAu5CEpEuN1Ai1X6cz+P47qV2LieKoWOwqCoY5rya9hPqAg7hNk6CceOUPQnOCbNnf4zQiDf9DW0b/WQQt+/4cM+eWondn3LaNYJV/5b9wXL3+2GMy2Dd4h/Ktsac2n51Ibs8gQwjCxfjAan8LgFJein4S6d3JQHgEttSp/+LizThHt8oWNPvNyMh6Zsajxxsm0rM7eRNlZI5Yy9E5hoJMKW3obmktBuSQzBGXUnJxRBUuXv//eVpXeFMAONJ8ZwzPBmAVffn5K/Mz2CqL1EjrU2RO0WSaTWyk26mODDN1iovOBJBXxTg3deH9o8dWvRRHQ==
  template:
    metadata:
      labels:
        app: guild
      name: guild-secret
      namespace: default
