apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-secretstore
  namespace: external-secrets
spec:
  provider:
    gcpsm:
      projectID: project-d29ff022-8c65-49c1-9db 
      auth:
        workloadIdentity:
          clusterLocation: asia-southeast2-a
          clusterName: dev-cluster
          serviceAccountRef:
            name: externalsecrets-ksa
            namespace: external-secrets