apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets
resources:
  - ../../base
  - ./gcp-secretstore.yaml
  - ./git-credential-secret.yaml
patches:
  - path: ./serviceaccount-patch.yaml