apiVersion: v1
kind: ServiceAccount
metadata:
  name: externalsecrets-ksa
  annotations:
    iam.gke.io/gcp-service-account: external-secrets-operator@project-d29ff022-8c65-49c1-9db.iam.gserviceaccount.com