name: Scale up dev cluster nodes to 3

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for running"
        required: false
        default: "Manual run"


jobs:
  scale-up:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          cli_config_credentials_token: ${{ secrets.HCP_API_TOKEN }}
      - run: terraform init
      - name: Perform node scaling
        run: terraform apply -var "dev_node_count=3" -auto-approve
