apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-ingressroute
  namespace: argocd
  labels:
    app: argocd
spec:
  entryPoints:
    - web
    # - websecure
  routes:
    - match: PathPrefix(`/api/webhook`)
      kind: Rule
      services:
        - name: argocd-server
          port: 80
          # scheme: https
